### ISSUE TITLE
Kip's review

### ISSUE THREAD

**Issue by gwenchee** [gwenchee/ms-thesis#4]
This issue can be closed when Kip reviews Chapter 1 and 2 of my thesis (pages 1 to 9 of this PDF). 
[ms-thesis.pdf](https://github.com/gwenchee/ms-thesis/files/3672406/ms-thesis.pdf)

**Comment by kipk49** [comment]
[ms-thesis-edit-pg1-9.pdf](https://github.com/gwenchee/ms-thesis/files/3691432/ms-thesis-edit-pg1-9.pdf)
