### ISSUE TITLE
kip review chapter 3

### ISSUE THREAD

**Issue by gwenchee** [gwenchee/ms-thesis#5]
This issue can be closed after @kipk49 reviews chapter 3 of this thesis. 
[ms-thesis.pdf](https://github.com/gwenchee/ms-thesis/files/3704152/ms-thesis.pdf)

**Comment by gwenchee** [comment]
Some sections of chapter 3 are repeats of the ddca journal article, so u can just skim through those parts. Thanks @kipk49 !

**Comment by kipk49** [comment]
[ms-thesis-ch3edits.pdf](https://github.com/gwenchee/ms-thesis/files/3741385/ms-thesis-ch3edits.pdf)
