### ISSUE TITLE
kip review chapter 4 & 5

### ISSUE THREAD

**Issue by gwenchee** [gwenchee/ms-thesis#6]
This issue can be closed after Kip reviews chapter 4 & 5 of this thesis. Thanks Kip! 
[ms-thesis.pdf](https://github.com/gwenchee/ms-thesis/files/3741413/ms-thesis.pdf)

**Comment by gwenchee** [comment]
You're the best @kipk49

**Comment by kipk49** [comment]
[ms-thesis-ch45edits.pdf](https://github.com/gwenchee/ms-thesis/files/3741497/ms-thesis-ch45edits.pdf)

**Comment by gwenchee** [comment]
@kipk49 You didn't edit the document that I linked here. There has been updates since the old versions of the thesis

**Comment by kipk49** [comment]
[ms-thesis-ch45edits-v2.pdf](https://github.com/gwenchee/ms-thesis/files/3744824/ms-thesis-ch45edits-v2.pdf)

oops

**Comment by gwenchee** [comment]
Thanks!
